[server]
enabled = true
address = "0.0.0.0"
port = 5656

  [server.keys]
  public = "id_server.pub"
  private = "id_server"

  [[server.channels]]
  name   = "home"
  admins = "fingerprint here"
  hidden = true
